### ISSUE TITLE
No such file or directory @ rb_sysopen

### ISSUE THREAD

**Issue by mikeRozen** [rubiconba/fastlane-plugin-flutter-version-manager#1]
Hi,
I have the following issue:
**bundle exec fastlane ios_beta_app** fails at the end 
I tried different paths for the _version.yml_
the lane directory is:
_/Users/myuser/AndroidStudioProjects/any_drive_student/ios/fastlane_
while the _version.yml_ and _pubspec.yaml_ are in the root 

   
```
[17:51:01]: No such file or directory @ rb_sysopen - ../../version.yml

+------+---------------------------+-------------+
|                fastlane summary                |
+------+---------------------------+-------------+
| Step | Action                    | Time (in s) |
+------+---------------------------+-------------+
| 1    | default_platform          | 0           |
| 2    | pwd                       | 0           |
| 3    | build_app                 | 135         |
| 4    | firebase_app_distribution | 40          |
| 💥   | flutter_version_manager   | 0           |
+------+---------------------------+-------------+

[17:51:01]: fastlane finished with errors

[17:51:01]: Error accessing file, this might be due to fastlane's directory handling
[17:51:01]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details

bundler: failed to load command: fastlane (/Users/myuser/.gems/bin/fastlane)

```

Fastfile:

```
default_platform(:ios)

platform :ios do
  desc "New iOS build for Counter Demo app"
    lane :ios_beta_app do
        sh "pwd"
        build_app(
            scheme: "Runner",
            archive_path: "./build/Runner.xcarchive",
            export_method: "development",
            output_directory: "./build/Runner"
        )
        firebase_app_distribution(
            app: "XXX",
            testers: "",
            release_notes: "Initial test version of the app",
            firebase_cli_path: "/usr/local/bin/firebase",
            ipa_path: "./build/Runner/AnyDrive-Student.ipa"
        )
        flutter_version_manager(
            arguments: "-patch",
            yml: "../../version.yml",
            pubspec: "../../pubspec.yaml")
    end
end
```
Please suggest what can be done?
Thanks a lot

**Comment by davormaricdev** [comment]
Hello, it looks like the plugin was unable to find the path to your version.yml
Can you show me your folder structure?

**Comment by mikeRozen** [comment]
Agree so I tried different paths, and had the same result. (_../../version.yml , /../../version.yml, ./version.yml_)
<img width="308" alt="Screen Shot 2020-11-14 at 8 11 07" src="https://user-images.githubusercontent.com/11506268/99141187-62febc00-2651-11eb-8ef7-1ee34a774960.png">

**Comment by davormaricdev** [comment]
Setting your path to be one level up should work if you run `fastlane [command]` from `ios` folder:

```
flutter_version_manager(
            arguments: "-patch",
            yml: "../version.yml",
            pubspec: "../pubspec.yaml")
```
You can read more about how fastlane handles directories [here](https://docs.fastlane.tools/advanced/fastlane/#directory-behavior).

However, I strongly recommend that you move fastlane one level up so you can use it to build and deploy both android and iOS applications from one place.
In order to do so, please follow these steps:
- Go to the root of your flutter application and run `fastlane init` (ignore warnings about missing XCode directory)
- Run `fastlane add_plugin flutter_version_manager` and follow the procedure
- Create `version.yml` file as specified [here](https://github.com/rubiconba/fastlane-plugin-flutter-version-manager/blob/master/version.yml)
- Navigate to the fastlane folder
- Open `Pluginfile` and add `gem 'git'` at the end
- Create new `Appfile` and add test lane which you can find [here](https://github.com/rubiconba/fastlane-plugin-flutter-version-manager/blob/master/fastlane/Fastfile)
- Go back to the root of your flutter application and try running `fastlane test` from your command line and see if that works.

Note: If you experience the _.git: [!] path does not exist (ArgumentError)_ error, you should add optional `git_repo` argument which should point out to the folder containing a .git folder.

**Comment by mikeRozen** [comment]
Hi,
So indeed according to docs every plugin runs in the root directory (which I believe in my case it's IOS or Android folder ), by changing to what you suggested and adding the _git_repo_ the plugin finished successfully BUT it doesn't get uploaded to firebase for some reason I tried to change the minor, patch number but still, I don't see it in Firebase, any suggestions?

**Comment by davormaricdev** [comment]
I haven't worked with firebase deployment that much, but I'd be best if you called `flutter_version_manager` followed by `flutter build ios` before `build_app` to ensure that the build number and version name is applied correctly
